# Generated by Django 5.2 on 2025-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_title_per_day',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_category_name'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('title',), name='task_manager_task'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='task_manager_category',
        ),
    ]
